services:

  api:
    build: ./api
    ports:
      - 5000:5000
    networks:
      - live_prometheus

  prometheus:
    image: prom/prometheus:v2.47.2
    ports:
      - 9090:9090
    networks:
      - live_prometheus


networks:
  live_prometheus:
    driver: bridge


