services:

  api:
    build: ./api
    ports:
      - 5000:5000
    networks:
      - live_prometheus

  prometheus:
    image: prom/prometheus:v2.47.2
    ports:
      - 9090:9090
    networks:
      - live_prometheus
    volumes:
      - ./Observability/prometheus.yaml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:10.2.2
    ports:
      - 3000:3000
    networks:
      - live_prometheus

networks:
  live_prometheus:
    driver: bridge


