global:
  scrape_interval: "15s"
  scrape_timeout: "5s"
  evaluation_interval: "1m"


scrape_configs:
  - job_name: api
    static_configs:
      - targets: ["api:5000"]
  
  - job_name: prometheus
    static_configs:
      - targets: ["prometheus:9090"]